# Generated by Django 3.1 on 2020-08-09 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'allergens',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('product_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name_kr', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('allergens', models.ManyToManyField(to='drinks.Allergen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.category')),
            ],
            options={
                'db_table': 'drinks',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.DecimalField(decimal_places=3, max_digits=8)),
                ('saturated_fat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sodium', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sugar', models.DecimalField(decimal_places=3, max_digits=8)),
                ('caffeine', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kr', models.CharField(max_length=32, null=True)),
                ('name_en', models.CharField(max_length=32, null=True)),
                ('milliliter', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('fluid_ounce', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.drink')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='drink',
            name='nutrition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drinks.nutrition'),
        ),
        migrations.AddField(
            model_name='drink',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.size'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.drink')),
            ],
            options={
                'db_table': 'descriptions',
            },
        ),
    ]
